### ISSUE TITLE
TypeError: Object #<Object> has no method 'execSync'

### ISSUE THREAD

**Issue by gavinengel** [Kikobeats/oh-my-terminal#1]
Using your first example I get the error: "TypeError: Object #<Object> has no method 'execSync'".

Here is my index.js file:

```
var terminal = require('oh-my-terminal')
var term = terminal.exec('echo hello world');
console.log(term);
```

```
[/_/Workspace/gits/wireframer]$ node .scripts/jade.js 

/home/gavin/MEGA/Workspace/gits/wireframer/node_modules/oh-my-terminal/lib/index.coffee:37
          return process.execSync(args.command, args.options);
                         ^
TypeError: Object #<Object> has no method 'execSync'
  at Function.module.exports.Terminal.exec (/home/gavin/MEGA/Workspace/gits/wireframer/node_modules/oh-my-terminal/lib/index.coffee:19:22)
  at Object.<anonymous> (/home/gavin/MEGA/Workspace/gits/wireframer/.scripts/jade.js:28:21)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:929:3
```

**Comment by Kikobeats** [comment]
what version of node are you using? You need `0.11` or high because `execSync` is a native method in the node api

**Comment by gavinengel** [comment]
Ah gotcha, I believe that's the problem.  Thanks.

**Comment by roughpandaz** [comment]
@Kikobeats Damn. they should have that in the docs. So I guess no sync for 0.10 then.

**Comment by Kikobeats** [comment]
@RongxinZhang see travis. tests pass from all stable node version, including 0.10.

BTW, I made a little refactor to be more easy read te code; but yes, the library support run in 0.10 as well.

**Comment by roughpandaz** [comment]
Awesome thanks man!
